version: "3"

services:
  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: IOTUCO
      POSTGRES_PASSWORD: LifeIsIoT
    ports:
      - "5432:5432"
    networks:
      pet-plate-red:
        ipv4_address: 192.168.1.2
  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: IOTUCO
      MONGO_INITDB_ROOT_PASSWORD: LifeIsIoT
    ports:
      - "27017:27017"
    networks:
      pet-plate-red:
        ipv4_address: 192.168.1.3
  frontend:
    image: brayanesq/pet-plate-frontend:v1.5
    ports:
      - "80:80"
    networks:
      pet-plate-red:
        ipv4_address: 192.168.1.4
  backend1:
    image: brayanesq/pet-plate-backend:v1.3
    ports:
      - "8080:8080"
    networks:
      pet-plate-red:
        ipv4_address: 192.168.1.5
  backend2:
    image: brayanesq/pet-plate-backend2:v1.1
    ports:
      - "4000:4000"
    networks:
      pet-plate-red:
        ipv4_address: 192.168.1.6
  chatbot:
    image: brayanesq/pet-plate-chatbot:v1.3
    ports:
      - "3030:3030"
    networks:
      pet-plate-red:
        ipv4_address: 192.168.1.7

networks:
  pet-plate-red:
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24

volumes:
  mongodb-data:
    driver: local
  postgres-data:
    driver: local